//tag::ref-doc[]
= SFTP Source

This source app supports transfer of files using the SFTP protocol.
Files are transferred from the `remote` directory to the `local` directory where the application is deployed.

Messages emitted by the source are provided as a byte array by default. However, this can be
customized using the `--mode` option:

- *ref* Provides a `java.io.File` reference
- *lines* Will split files line-by-line and emit a new message for each line
- *contents* The default. Provides the contents of a file as a byte array

When using `--mode=lines`, you can also provide the additional option `--withMarkers=true`.
If set to `true`, the underlying `FileSplitter` will emit additional _start-of-file_ and _end-of-file_ marker messages before and after the actual data.
The payload of these 2 additional marker messages is of type `FileSplitter.FileMarker`. The option `withMarkers` defaults to `false` if not explicitly set.

When configuring the `sftp.factory.known-hosts-expression` option, the root object of the evaluation is the application context, an example might be `sftp.factory.known-hosts-expression = @systemProperties['user.home'] + '/.ssh/known_hosts'`.

See also https://github.com/spring-cloud-stream-app-starters/core/blob/master/common/app-starters-metadata-store-common/README.adoc[`MetadataStore`] options for possible shared persistent store configuration for the `FtpPersistentAcceptOnceFileListFilter` and `IdempotentReceiverInterceptor` used in the FTP Source.



[NOTE]
This app is designed to work with CloundFoundry(2.3+) Volume Services. The app will be automatically configured to use
CloundFoundry Volume Services when running in CloudFoundy with the `nfs` service enabled and bound.  If using
CloudFoundry volume services, `local-dir` is always interpreted as relative to the bound nfs service instance's mount
point. The default `local-dir`, something like `Paths.get(System("java.io.tmpdir"),"sftp-source")` This will work
fine for downstream apps that are also bound to nfs and consume the path in the message payload, but may be inconvenient
for external access. The assumption is if the service is present, the intention is to use it. For non-container environments,
relative and absolute paths work as expected. If `list-only=true` or `stream=true` the remote file will not be downloaded in any case.

[NOTE]
In contrast to previous versions which support task launch requests, this app uses spring-cloud-stream function
support and built-in functions `standaloneTaskLaunchRequest` and `dataflowTaskLaunchRequest` to optionally transform
the output payload to use as input to one of the standard `task-launcher` sinks. This feature is enabled by setting
the `spring.cloud.stream.function.definition` property to include one of the above function names. It is recommended
to set `list-only=false` and `file-mode=ref` (the defaults) when using this feature. In this case, the remote file
will be downloaded to the `local-dir`, which can also by an NFS mounted directory. If `list-only=true`, the task
launch request will include sftp connection parameters and the remote path, and the task will be responsible for
downloading the file.

== Input

N/A (Fetches files from an SFTP server).

== Output

=== mode = contents

==== Headers:

* `Content-Type: application/octet-stream`
* `file_originalFile: <java.io.File>`
* `file_name: <file name>`

==== Payload:

A `byte[]` filled with the file contents.

=== mode = lines

==== Headers:

* `Content-Type: text/plain`
* `file_originalFile: <java.io.File>`
* `file_name: <file name>`
* `correlationId: <UUID>` (same for each line)
* `sequenceNumber: <n>`
* `sequenceSize: 0` (number of lines is not know until the file is read)

==== Payload:

A `String` for each line.

The first line is optionally preceded by a message with a `START` marker payload.
The last line is optionally followed by a message with an `END` marker payload.

Marker presence and format are determined by the `with-markers` and `markers-json` properties.

=== mode = ref

==== Headers:

None.

==== Payload:

A `java.io.File` object, byte stream, or file contents.

=== spring.cloud.stream.function.definition=standaloneTaskLaunchRequest

==== Headers:

* `Content-Type: application/json`

==== Payload:

A https://docs.spring.io/spring-cloud-task/docs/current/apidocs/org/springframework/cloud/task/launcher/TaskLaunchRequest.html[TaskLaunchRequest] object.
with the following settings:

* command line arguments (also bound to job parameters for Spring Batch):
** `<task.local-file-path-parameter-name>`=`<task.local-file-path-parameter-value>`
** `<task.remote-file-path-parameter-name>`=`<task.remote-file-path-parameter-value>` if `list-only=true`

* `task.environment-properties` added to the task system environment
*  sftp connection parameters added to the task system environment if `list-only=true`

* `task.resource-uri` is required.
* `task.deployment-properties` and `task.environment-properties` are optional.
* `task.application-name` is ignored and will be generated.


=== spring.cloud.stream.function.definition=dataflowTaskLaunchRequest

==== Headers:

* `Content-Type: application/json`

==== Payload:

A DataFlow Task Launch request as JSON: `{"name":"<task.application-name>", "deploymentProps":{"key"="val",...},
"args":[]}`
with the following set as command line arguments (also bound to job parameters for Spring Batch):

* `<task.local-file-path-parameter-name>`=`<task.local-file-path-parameter-value>`
* `<task.remote-file-path-parameter-name>`=`<task.remote-file-path-parameter-value>` and sftp connection parameters,
if `list-only=true`
*  Any provided `task.parameters`

* `task.resource-uri` is ignored (already registered in Data Flow Server).
* `task.environment-properties` is ignored (configured is Data Flow Server).
* `task.deployment-properties` is optional.
* `task.application-name` is required (the Data Flow Task Name).

== Options

The **$$sftp$$** $$source$$ has the following options:

//tag::configuration-properties[]
$$file.consumer.markers-json$$:: $$When 'fileMarkers == true', specify if they should be produced as FileSplitter.FileMarker objects or JSON.$$ *($$Boolean$$, default: `$$true$$`)*
$$file.consumer.mode$$:: $$The FileReadingMode to use for file reading sources. Values are 'ref' - The File object, 'lines' - a message per line, or 'contents' - the contents as bytes.$$ *($$FileReadingMode$$, default: `$$<none>$$`, possible values: `ref`,`lines`,`contents`)*
$$file.consumer.with-markers$$:: $$Set to true to emit start of file/end of file marker messages before/after the data. 	Only valid with FileReadingMode 'lines'.$$ *($$Boolean$$, default: `$$<none>$$`)*
$$sftp.auto-create-local-dir$$:: $$Set to true to create the local directory if it does not exist.$$ *($$Boolean$$, default: `$$true$$`)*
$$sftp.delete-remote-files$$:: $$Set to true to delete remote files after successful transfer.$$ *($$Boolean$$, default: `$$false$$`)*
$$sftp.directories$$:: $$A list of factory "name.directory" pairs.$$ *($$String[]$$, default: `$$<none>$$`)*
$$sftp.factories$$:: $$A map of factory names to factories.$$ *($$Map<String, Factory>$$, default: `$$<none>$$`)*
$$sftp.factory.allow-unknown-keys$$:: $$True to allow an unknown or changed key.$$ *($$Boolean$$, default: `$$false$$`)*
$$sftp.factory.cache-sessions$$:: $$Cache sessions$$ *($$Boolean$$, default: `$$<none>$$`)*
$$sftp.factory.host$$:: $$The host name of the server.$$ *($$String$$, default: `$$localhost$$`)*
$$sftp.factory.known-hosts-expression$$:: $$A SpEL expression resolving to the location of the known hosts file.$$ *($$Expression$$, default: `$$<none>$$`)*
$$sftp.factory.pass-phrase$$:: $$Passphrase for user's private key.$$ *($$String$$, default: `$$<empty string>$$`)*
$$sftp.factory.password$$:: $$The password to use to connect to the server.$$ *($$String$$, default: `$$<none>$$`)*
$$sftp.factory.port$$:: $$The port of the server.$$ *($$Integer$$, default: `$$22$$`)*
$$sftp.factory.private-key$$:: $$Resource location of user's private key.$$ *($$String$$, default: `$$<empty string>$$`)*
$$sftp.factory.username$$:: $$The username to use to connect to the server.$$ *($$String$$, default: `$$<none>$$`)*
$$sftp.fair$$:: $$True for fair polling of multiple servers/directories.$$ *($$Boolean$$, default: `$$false$$`)*
$$sftp.filename-pattern$$:: $$A filter pattern to match the names of files to transfer.$$ *($$String$$, default: `$$<none>$$`)*
$$sftp.filename-regex$$:: $$A filter regex pattern to match the names of files to transfer.$$ *($$Pattern$$, default: `$$<none>$$`)*
$$sftp.list-only$$:: $$Set to true to return file metadata without the entire payload.$$ *($$Boolean$$, default: `$$false$$`)*
$$sftp.local-dir$$:: $$The local directory (or target location) to use for file transfers.$$ *($$File$$, default: `$$<none>$$`)*
$$sftp.max-fetch$$:: $$The maximum number of remote files to fetch per poll; default unlimited. Does not apply when listing files or building task launch requests.$$ *($$Integer$$, default: `$$<none>$$`)*
$$sftp.preserve-timestamp$$:: $$Set to true to preserve the original timestamp.$$ *($$Boolean$$, default: `$$true$$`)*
$$sftp.remote-dir$$:: $$The remote FTP directory.$$ *($$String$$, default: `$$/$$`)*
$$sftp.remote-file-separator$$:: $$The remote file separator.$$ *($$String$$, default: `$$/$$`)*
$$sftp.stream$$:: $$Set to true to stream the file rather than copy to a local directory.$$ *($$Boolean$$, default: `$$false$$`)*
$$sftp.task.application-name$$:: $$<documentation missing>$$ *($$String$$, default: `$$<none>$$`)*
$$sftp.task.data-source-password$$:: $$<documentation missing>$$ *($$String$$, default: `$$<none>$$`)*
$$sftp.task.data-source-url$$:: $$<documentation missing>$$ *($$String$$, default: `$$<none>$$`)*
$$sftp.task.data-source-user-name$$:: $$<documentation missing>$$ *($$String$$, default: `$$<none>$$`)*
$$sftp.task.deployment-properties$$:: $$<documentation missing>$$ *($$String$$, default: `$$<none>$$`)*
$$sftp.task.environment-properties$$:: $$<documentation missing>$$ *($$String$$, default: `$$<none>$$`)*
$$sftp.task.local-file-path-parameter-name$$:: $$Value to use as the local file parameter name.$$ *($$String$$, default: `$$localFilePath$$`)*
$$sftp.task.parameters$$:: $$<documentation missing>$$ *($$List<String>$$, default: `$$<none>$$`)*
$$sftp.task.remote-file-path-parameter-name$$:: $$Value to use as the remote file parameter name.$$ *($$String$$, default: `$$remoteFilePath$$`)*
$$sftp.task.resource-uri$$:: $$<documentation missing>$$ *($$String$$, default: `$$<none>$$`)*
$$sftp.tmp-file-suffix$$:: $$The suffix to use while the transfer is in progress.$$ *($$String$$, default: `$$.tmp$$`)*
$$trigger.cron$$:: $$Cron expression value for the Cron Trigger.$$ *($$String$$, default: `$$<none>$$`)*
$$trigger.date-format$$:: $$Format for the date value.$$ *($$String$$, default: `$$<none>$$`)*
$$trigger.fixed-delay$$:: $$Fixed delay for periodic triggers.$$ *($$Integer$$, default: `$$1$$`)*
$$trigger.initial-delay$$:: $$Initial delay for periodic triggers.$$ *($$Integer$$, default: `$$0$$`)*
$$trigger.max-messages$$:: $$Maximum messages per poll, -1 means infinity.$$ *($$Long$$, default: `$$-1$$`)*
$$trigger.time-unit$$:: $$The TimeUnit to apply to delay values.$$ *($$TimeUnit$$, default: `$$SECONDS$$`, possible values: `NANOSECONDS`,`MICROSECONDS`,`MILLISECONDS`,`SECONDS`,`MINUTES`,`HOURS`,`DAYS`)*
//end::configuration-properties[]

== Build

```
$ ./mvnw clean install -PgenerateApps
$ cd apps
```
You can find the corresponding binder based projects here.
You can then cd into one one of the folders and build it:
```
$ ./mvnw clean package
```

== Examples

```
java -jar sftp_source.jar --sftp.remote-dir=foo --file.consumer.mode=lines --trigger.fixed-delay=60 \
         --sftp.factory.host=sftpserver --sftp.factory.username=user --sftp.factory.password=pw --sftp.local-dir=/foo
```
//end::ref-doc[]
